const words = ['Bearcat',
        'Armadillo',
        'Porcupine',
        'Peacock',
        'Alligator',
        'Nightingale',
        'Woodchuck',
        'Woodpecker',
        'Elephant',
        'Antelope',
        'Pronghorn',
        'Penguin',
        'Grasshopper',
        'Hummingbird',
        'Mosquito',
        'armpit',
        'chocolate',
        'brown',
        'forever',
        'passport',
        'initiate',
        'migrant',
        'president',
        'hamburger'];


const letters=['A', 'B', 'C', 'D', 'E',
            'F', 'G', 'H', 'I', 'J', 'K',
            'L', 'M', 'N', 'O', 'P', 'Q',
            'R', 'S', 'T', 'U', 'V', 'W',
            'X', 'Y', 'Z'];
